global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
    # This IP seems to be static (not sure why the DHCP server always assigns the same IP)
    # In any case, you can check on your machine which IP corresponds to cadvisor by executing
    # docker inspect cadvisor --format '{{.NetworkSettings.Networks.bridge.IPAddress}}'
      - targets: ['172.17.0.3:8080']