
index_parameter_templates:
  default:
    ef_construction: [128]
    # Define a list of efSearch values to be used for the benchmark
    ef_search: [128, 256]
    # Define a list of M values to be used for the benchmark
    max_edges_per_node: [32]

  dense_graph:
    ef_construction: [1024]
    ef_search: [512, 1024]
    max_edges_per_node: [512]

  # Potentially useful for conducting a more thorough benchmark. 
  exhaustive:
    ef_construction: [16, 32, 64, 128, 256, 512, 1024]
    # 1024 might be an overkill, but I don't really know how to properly 
    # set this parameter, so for now it's just going to be trail and error. 
    # And I like powers of 2. 
    ef_search: [16, 32, 64, 128, 256, 512, 1024]
    max_edges_per_node: [8, 16, 32, 64, 128, 256, 512]
  
datasets:
- name: "mnist-784-euclidean"
  index_parameter_template: "default"
  train_file: "data/mnist-784-euclidean/mnist-784-euclidean.train.npy"
  gtruth_file: "data/mnist-784-euclidean/mnist-784-euclidean.gtruth.npy"
  test_file: "data/mnist-784-euclidean/mnist-784-euclidean.test.npy"
  train_size: 60000
  test_size: 10000
  neighbors: 100
  dim: 784
  metric_id: 0

- name: "gist-960-euclidean"
  index_parameter_template: "default"
  train_file: "data/gist-960-euclidean/gist-960-euclidean.train.npy"
  gtruth_file: "data/gist-960-euclidean/gist-960-euclidean.gtruth.npy"
  test_file: "data/gist-960-euclidean/gist-960-euclidean.test.npy"
  train_size: 1000000
  test_size: 1000
  neighbors: 100
  dim: 960
  metric_id: 0

- name: "glove-200-angular"
  index_parameter_template: "default"
  train_file: "data/glove-200-angular/glove-200-angular.train.npy"
  gtruth_file: "data/glove-200-angular/glove-200-angular.gtruth.npy"
  test_file: "data/glove-200-angular/glove-200-angular.test.npy"
  train_size: 1000000
  test_size: 10000
  neighbors: 100
  dim: 200
  metric_id: 1

- name: "glove-25-angular"
  index_parameter_template: "default"
  train_file: "data/glove-25-angular/glove-25-angular.train.npy"
  gtruth_file: "data/glove-25-angular/glove-25-angular.gtruth.npy"
  test_file: "data/glove-25-angular/glove-25-angular.test.npy"
  train_size: 1183514
  test_size: 10000
  neighbors: 100
  dim: 25
  metric_id: 1

- name: "glove-100-angular"
  index_parameter_template: "default"
  train_file: "data/glove-100-angular/glove-100-angular.train.npy"
  gtruth_file: "data/glove-100-angular/glove-100-angular.gtruth.npy"
  test_file: "data/glove-100-angular/glove-100-angular.test.npy"
  train_size: 1183514
  test_size: 10000
  neighbors: 100
  dim: 100
  metric_id: 1

- name: "glove-200-angular"
  index_parameter_template: "default"
  train_file: "data/glove-200-angular/glove-200-angular.train.npy"
  gtruth_file: "data/glove-200-angular/glove-200-angular.gtruth.npy"
  test_file: "data/glove-200-angular/glove-200-angular.test.npy"
  train_size: 1183514
  test_size: 10000
  neighbors: 100
  dim: 200
  metric_id: 1

- name: "sift-128-euclidean"
  index_parameter_template: "default"
  train_file: "data/sift-128-euclidean/sift-128-euclidean.train.npy"
  gtruth_file: "data/sift-128-euclidean/sift-128-euclidean.gtruth.npy"
  test_file: "data/sift-128-euclidean/sift-128-euclidean.test.npy"
  train_size: 1000000
  test_size: 10000
  neighbors: 100
  dim: 128
  metric_id: 0

- name: "deep-image-96-angular"
  index_parameter_template: "default"
  train_file: "data/deep-image-96-angular/deep-image-96-angular.train.npy"
  gtruth_file: "data/deep-image-96-angular/deep-image-96-angular.gtruth.npy"
  test_file: "data/deep-image-96-angular/deep-image-96-angular.test.npy"
  train_size: 9990000
  test_size: 10000
  neighbors: 100
  dim: 96
  metric_id: 1



