# name: Run Tests

# on: [pull_request]

# env: 
#   POETRY_VERSION: "1.6.1"

# jobs:
#   build-and-test:
#     strategy:
#       # Ensure that failure for one test does not cancel other 
#       # actions 
#       fail-fast: false
#       matrix:
#         # TODO: Get macos-latest to work as well
#         os: [ubuntu-latest] 
#         python-version: ['3.9', '3.10', '3.11']
#     runs-on: ${{ matrix.os }}
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v3
#       with:
#         submodules: 'recursive'

#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v4
#       with:
#         python-version: ${{ matrix.python-version }}

#     - name: Set up Poetry
#       uses: snok/install-poetry@v1
#       with:
#         version: ${{ env.POETRY_VERSION }}

#     - name: Install libomp (MacOS)
#       if: runner.os == 'macOS'
#       run: brew install libomp 

#     - name: Install dependencies
#       run: |
#         cd flatnav_python
#         poetry install 

#     - name: Build flatnav 
#       run: |
#         cd flatnav_python
#         export NO_MANUAL_VECTORIZATION=1
#         ./install_flatnav.sh

#     - name: Run Unit Tests
#       run: |
#         cd flatnav_python
#         poetry run pytest -vs unit_tests
